### PR TITLE
add remember me function

### PR DESCRIPTION
**Pull request by funny-cat-happy**
添加了记住我功能，可以记住账号和密码并放在localStorage中，为了安全考虑密码做了一点编码加密

### CODE REVIEW

**Comment by moeakwak** [comment]
请在 vscode 中启用 eslint 插件。views/login/index.vue 有多条报错，有许多类型错误。

**Comment by funny-cat-happy** [comment]
> 请在 vscode 中启用 eslint 插件。views/login/index.vue 有多条报错，有许多类型错误。

我知道有很多类型错误，但是找了很多资料后修复不了，我是逐句按照你的代码抄的，但是奇怪的是你的代码不报错我的代码会报错。我看了一下全是TS的错误

**Review by spammenotinoz — APPROVED** [review]

**Comment by spammenotinoz** [comment]
Hi, I was looking at this again today, and assuming you are not restarting your service regularly, if you are trying to improve the user experience, couldn't you just increase the values of jwt_lifetime_seconds and cookie_max_age
These are currently set to 1 day, but increasing to a week may reduce the need to login again.

**Comment by spammenotinoz** [comment]
I increased "jwt_lifetime_seconds and cookie_max_age" to 1 week and it is working quite well, I have not been prompted for a login for ~4days and counting.

**Pull request closed without merging**
